swagger: "2.0"
info:
  description: File swagger per configurazione dell'endpoint
  version: "1.0.0"
  title: File swagger per REST API
consumes:
  -  application/json
produces:
  -  application/json

basePath: /api

# Percorsi gestibili
paths:
  /persone:
    # Legge tutte le persone
    get:
      operationId: persone.read
      tags:
        - Persone - Live
      summary: Legge tutte le persone nella variabile live
      description: Legge la lista di persone live.
      responses:
        200:
          description: Operazione di lettura effettuata con successo
          schema:
            type: array
            items:
              properties:
                name:
                  type: string

  /persone/casuale/:
    # Estrae una persona casuale (se viene passato {nome} lo ignora dall'estrazione)
    post:
      operationId: persone.estrai
      tags:
        - Persone - Live
      summary: Estrae una persona casuale dalla lista live
      description: Estrae casualmente una persona dalla lista, la persona estratta viene eliminata dalla variabile live. Questa operazione non ha effetto sul file statico e verrà dimenticata al riavvio del server.
      parameters:
        - name: nome
          in: body
          description: persona da ignorare nell'estrazione
          required: False
          schema:
            type: object
      responses:
        200:
          description: Estrazione effettuata con successo
          schema:
            properties:
              nome:
                type: string
                description: Nome della persona estratta

  /persone/static/read:
    # Legge tutte le persone
    get:
      operationId: persone.read_static
      tags:
        - Persone - Static
      summary: Legge tutte le persone dal file statico
      description: Legge la lista di persone statica. Si aggiorna solo se effettuata un'operazione statica
      responses:
        200:
          description: Operazione di lettura effettuata con successo
          schema:
            type: array
            items:
              properties:
                name:
                  type: string

  /persone/static/{nome}:
    # Crea una nuova persona
    post:
      operationId: persone.create
      tags:
        - Persone - Static
      summary: Crea una nuova persona e la aggiunge alla lista
      description: Crea una nuova persona. Il cambiamento è permanente ed effettuato sul file statico
      parameters:
        - name: nome
          in: path
          description: Persona da creare
          type: string
          required: True
      responses:
        201:
          description: Persona creata

    # Elimina una persona dalla lista
    delete:
      operationId: persone.delete
      tags:
        -  Persone - Static
      summary:  Elimina una persona dalla lista
      description:  Elimina una persona. Il cambiamento è permanente ed effettuato sul file statico
      parameters:
        - name: nome
          in: path
          description: Persona da eliminare
          type: string
          required: True
      responses:
        200:
          description: Persona eliminata con successo
